[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
inktrust_core = "D8w7y2m9VywSfAMG48dgiroienfrX419wjESVxPyv4sR"

[programs.devnet]
inktrust_core = "D8w7y2m9VywSfAMG48dgiroienfrX419wjESVxPyv4sR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
